// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATVna-o6ofovRFRIhg_KmV18kT-ByC3qM',
    appId: '1:986803671130:web:0067f06675e343ffdec863',
    messagingSenderId: '986803671130',
    projectId: 'push-notifications-app-1',
    authDomain: 'push-notifications-app-1.firebaseapp.com',
    storageBucket: 'push-notifications-app-1.firebasestorage.app',
    measurementId: 'G-WLT402K03P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1bgSx_KPSIXIzVePlyNjFJtZfdIxPfCc',
    appId: '1:986803671130:android:8342720f4746ab4bdec863',
    messagingSenderId: '986803671130',
    projectId: 'push-notifications-app-1',
    storageBucket: 'push-notifications-app-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrUggXPyEw3jgVGaS9x23XzJHfNoyDuvU',
    appId: '1:986803671130:ios:1be85df58507301fdec863',
    messagingSenderId: '986803671130',
    projectId: 'push-notifications-app-1',
    storageBucket: 'push-notifications-app-1.firebasestorage.app',
    iosBundleId: 'com.example.notiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrUggXPyEw3jgVGaS9x23XzJHfNoyDuvU',
    appId: '1:986803671130:ios:1be85df58507301fdec863',
    messagingSenderId: '986803671130',
    projectId: 'push-notifications-app-1',
    storageBucket: 'push-notifications-app-1.firebasestorage.app',
    iosBundleId: 'com.example.notiapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATVna-o6ofovRFRIhg_KmV18kT-ByC3qM',
    appId: '1:986803671130:web:0def4cf268e9dea3dec863',
    messagingSenderId: '986803671130',
    projectId: 'push-notifications-app-1',
    authDomain: 'push-notifications-app-1.firebaseapp.com',
    storageBucket: 'push-notifications-app-1.firebasestorage.app',
    measurementId: 'G-YXG8W36R18',
  );
}
